name: mysql_client
description: A starting point for Dart libraries or applications.
version: 0.0.1
#author: Your Name <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.15.0 <2.0.0'

dependencies:
  crypto: "^1.0.0"
  pool: "^1.2.1"
dev_dependencies:
  stack_trace: "^1.6.0"
  test: '>=0.12.0 <0.13.0'
